import type { Metadata } from "next";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Poppins, Press_Start_2P } from "next/font/google";
import { routing } from "@/i18n/routing";
import { ThemeRegistry } from "@/components/providers/ThemeRegistry";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SiteFooter } from "@/components/layout/SiteFooter";
import "../globals.css";

const bodyFont = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-body",
  subsets: ["latin"],
});

const pixelFont = Press_Start_2P({
  weight: "400",
  variable: "--font-pixel",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  // Read the theme from a cookie on the server so `data-theme` is in the
  // initial HTML — no flash, and no client-side <script> (which React 19 warns
  // about when rendered inside a component).
  const cookieStore = await cookies();
  const theme = cookieStore.get("pc-theme")?.value === "light" ? "light" : "dark";

  return (
    <html
      lang={locale}
      data-theme={theme}
      className={`${bodyFont.variable} ${pixelFont.variable}`}
      suppressHydrationWarning
    >
      <body>
        <NextIntlClientProvider messages={messages}>
          <ThemeRegistry>
            <SiteHeader />
            {children}
            <SiteFooter />
          </ThemeRegistry>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
