import type { Metadata } from "next";
import Script from "next/script";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Poppins, Press_Start_2P } from "next/font/google";
import { routing } from "@/i18n/routing";
import { ThemeRegistry } from "@/components/providers/ThemeRegistry";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SiteFooter } from "@/components/layout/SiteFooter";
import "../globals.css";

const bodyFont = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-body",
  subsets: ["latin"],
});

const pixelFont = Press_Start_2P({
  weight: "400",
  variable: "--font-pixel",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} className={`${bodyFont.variable} ${pixelFont.variable}`} suppressHydrationWarning>
      <body>
        {/* Apply the saved theme before paint to avoid a flash / hydration mismatch.
            An external beforeInteractive script (not inline) avoids React 19's
            "script tag inside a component" warning while still running early. */}
        <Script src="/theme-init.js" strategy="beforeInteractive" />
        <NextIntlClientProvider messages={messages}>
          <ThemeRegistry>
            <SiteHeader />
            {children}
            <SiteFooter />
          </ThemeRegistry>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
